In [2]:
import numpy as np
import matplotlib.pyplot as plt


`np.linalg.norm(x, ord=None, axis=None, keepdims=False)`

x -> input array

ord ->  
&emsp;ord=2 (Euclidean norm) (default)  
&emsp;ord=1 (Manhattan norm)  
&emsp;many others for matrices

axis -> Determines the axis over which the norm is computed. `None` for vectors

keepdims -> If True, the reduced dimensions are kept as singleton dimensions.

In [ ]:
vector = np.array([3, 4])
magnitude = np.linalg.norm(vector, ord=2)  # Euclidean norm
print(magnitude) # math.sqrt(3**2 + 4**2)

5.0


In [5]:
vector = np.array([3, 4])
magnitude = np.linalg.norm(vector, ord=2, keepdims=True)  # Euclidean norm
print(magnitude, magnitude.shape) # math.sqrt(3**2 + 4**2)

[5.] (1,)


`array[:, np.newaxis]  # Adds a new axis at the specified position`  
 Increases the dimensionality of an array by 1 along the specified axis.

In [7]:
vector = np.array([1,2])
print(vector.shape)

arr_row = vector[:, np.newaxis]
print(arr_row, arr_row.shape)

arr_col = vector[np.newaxis, :]
print(arr_col, arr_col.shape)

(2,)
[[1]
 [2]] (2, 1)
[[1 2]] (1, 2)


In [23]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
print(matrix.shape)

# tensor1 = matrix[np.newaxis, :, :]
tensor1 = matrix[np.newaxis, :]
print(tensor1, tensor1.shape)

tensor2 = matrix[:, np.newaxis, :]
print(tensor2, tensor2.shape)

tensor3 = matrix[:, :, np.newaxis]
print(tensor3, tensor3.shape)

(3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]] (1, 3, 3)
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]] (3, 1, 3)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]] (3, 3, 1)


In [27]:
# What is the condition for adding and subtracting among tensors
mat1 = np.array([[1, 2]])
mat2 = np.array([
    [10, 20],
    [20, 30],
    [30, 40],
])

print(mat2 - mat1)
# This is called as brodcasting 
# https://www.youtube.com/watch?v=oG1t3qlzq14

[[ 9 18]
 [19 28]
 [29 38]]


In [59]:
# Frobenius Norm
# https://www.youtube.com/watch?v=yJh8l9HKMGY
# Bu default for matrices in np.linalg.norm (or use ord='fro')

mat = np.array([[1,2], [3,4]])
print(np.linalg.norm(mat, ord='fro'))
print(np.sqrt(1**2 + 2**2 + 3**2 + 4**2))

# (300, 1, 2)
# (3, 2)
# after brodcasting, resulted array shape is 
# (300, 3, 2)

# For simplicity, lets take (2, 3, 2)

tensor4 = np.array([
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    [
        [7, 8],
        [9, 10],
        [11, 12]
    ]
])
print(tensor4.shape)

print(np.linalg.norm(tensor4, axis=1))
print(np.linalg.norm(tensor4, axis=1).shape)

# For shape (4, 3, 2)

# When axis = 0
# res = (3, 2)

# When axis = 1
# res = (2, 2)

# When axis = 2
# res = (2, 3)

# axis = 0
# print(np.array(
#     [
#         [np.sqrt(1**2 + 7**2), np.sqrt(2**2 + 8**2)],
#         [np.sqrt(3**2 + 9**2), np.sqrt(4**2 + 10**2)],
#         [np.sqrt(5**2 + 11**2), np.sqrt(6**2 + 12**2)],
#     ]
# ))

# axis = 1
print(np.array(
    [
        [np.sqrt(1**2 + 3**2 + 5**2), np.sqrt(2**2 + 4**2 + 6**2)],
        [np.sqrt(7**2 + 9**2 + 11**2), np.sqrt(8**2 + 10**2 + 12**2)],
    ]
))

# axis = 2
# print(np.array(
#     [
#         [np.sqrt(1**2 + 2**2), np.sqrt(3**2 + 4**2), np.sqrt(5**2 + 6**2)],
#         [np.sqrt(7**2 + 8**2), np.sqrt(9**2 + 10**2), np.sqrt(11**2 + 12**2)]
#     ]
# ))

5.477225575051661
5.477225575051661
(2, 3, 2)
[[ 5.91607978  7.48331477]
 [15.84297952 17.54992877]]
(2, 2)
[[ 5.91607978  7.48331477]
 [15.84297952 17.54992877]]


The `np.argmin` function in NumPy is used to find the index of the smallest value in an array.  
It can operate on the entire array or along a specified axis.

In [71]:
# In 1D
a1 = np.array([10,9,1,2,3,4,5])
print(np.argmin(a1))
print(np.argmax(a1))

# In 2D
a2 = np.array([
    [10, 55, 12],
    [22, 21, 23],
])
print(np.argmin(a2, axis=0))
# print(np.argmax(a2, axis=0))

print(np.argmin(a2, axis=1))
# print(np.argmax(a2, axis=1))

# Shape: (2, 3)
# argmin / argmax for axis=0: (3,)
# argmin / argmax for axis=1: (2,)

2
0
[0 1 0]
[0 1]
